name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  AWS_DEFAULT_REGION: us-east-1 # Replace with your AWS region
  AWS_ACCOUNT_ID: AKIAUL4AP4BKPPXECWJR # Replace with your AWS account ID
  ECR_REPO: ecr-web-image # Replace with your ECR repository name
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 300380315732.dkr.ecr.us-east-1.amazonaws.com
      - name: Build Docker image
        run: |
          docker build -t ecr-web-image .
      
      - name: Tag Docker image
        run: |
          docker tag ecr-web-image:latest 300380315732.dkr.ecr.us-east-1.amazonaws.com/ecr-web-image:latest
      - name: Push Docker image to ECR
        run: |
          docker push 300380315732.dkr.ecr.us-east-1.amazonaws.com/ecr-web-image:latest